//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Expenses
{
    public int Id { get; set; }
    public string item { get; set; }
    public string price { get; set; }
    public string reason { get; set; }
    public Nullable<System.DateTime> date { get; set; }
}

public partial class Job
{
    public int Id { get; set; }
    public string task { get; set; }
    public Nullable<System.TimeSpan> start_time { get; set; }
    public Nullable<System.TimeSpan> end_time { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public Nullable<System.TimeSpan> duration { get; set; }
}

public partial class movy
{
    public int Id { get; set; }
    public string movie { get; set; }
    public string genre { get; set; }
    public string year { get; set; }
}
